name = "testing-webapp"
main = "src/index.js"
compatibility_date = "2026-10-05"

[[d1_databases]]
binding = "DB"
database_name = "testing-webapp-db"
database_id = "5c86eed2-43e7-4799-85fa-25ce59fc772a"
